version: '3'
services:
  node-app:
    image: nodejs:$TAG
    build: 
      context: .
      args:
        MONGODB_URI: $MONGODB_URI
    container_name: server
    ports:
       - "5000:4000"
    depends_on:
       - db
  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - my-volume:/data/db
    hostname: my-db-host
volumes:
  my-volume: