name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy DOcker Compose
        env:
          MONGODB_URI: ${{ env.MONGODB_URI }}
          TAG: ${{ github.run_number }}
        run: |
          docker-compose up -d
      
      - name: Push Docker
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag ${{ secrets.DOCKER_REGISTRY }}/nodejs:$TAG ${{ secrets.DOCKER_REGISTRY }}/nodejs:latest
          docker push ${{ secrets.DOCKER_REGISTRY }}/nodejs:latest
